donation/urls.py
from django.urls import path,include
from . import views

app_name = 'donation'

urlpatterns = [
# opens three options of adding donations ind bulk or anon
    path('add_don/',views.add_don,name='add_don'),
    path('don_ind/',views.don_ind,name='don_ind'),
    path('don_bulk/',views.don_bulk,name='don_bulk'),
    path('don_anon/',views.don_anon,name='don_anon'),
    path('don_added/',views.don_added,name='don_added'),
    path('view_don/',views.DonationListView.as_view(),name = 'view_don'),
    path('download/',views.download_rec,name = 'download_rec'),
    path('edit_misc/',views.set_prefix,name = 'edit_misc'),
    path('export_donation/',views.export_donation,name = 'export_donations'),
    path('resend_mails/',views.resend_mails,name = 'resend_mail'),
    path('edit_don/',views.edit_don,name = 'edit_don'),
    path('don_edited',views.don_edited,name = 'don_edited')
]

exptemp/urls.py
from django.urls import path
from . import views

app_name = 'exptemp'
urlpatterns=[
    path('addexp/',views.add_exp_view,name = 'add_exp'),
    path('genexp/',views.success,name = 'generate_exp'),
    path('storeexp/',views.generate_exp,name = 'store_exp'),
    path('appr_success/',views.appr_success,name = 'appr_success'),
 	path('viewexp/',views.view_old,name = 'viewoldexp'),
    path('settleexp/',views.settle_exp,name = 'settleexp'),  
    path('detailexp/<int:key_id>/', views.detail_exp, name='detailexp'),
    path('settleexpform/',views.settle_exp_form,name = 'settleexpform'),
	path('settled/',views.settled_view,name = 'settled'),
]

root_web/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='root'
urlpatterns = [
    #urls of admin site
    path('admin/', admin.site.urls),
    # root url points to the view that opens when there is nothing open
    path('',views.index,name='index'),
    # include the urls of supporters , when 'supp/' us encountered in url django goes to urls in supporter app
    path('supp/',include('supporters.urls')),
      # include the urls of donations , when 'don/' us encountered in url django goes to urls in donations app
    path('don/',include('donation.urls')),
      # include the urls of expenditure , when 'exp/' us encountered in url django goes to urls in expenditure app
    path('exp/',include('exptemp.urls')),
      # include the urls of usersreg , when 'user/' us encountered in url django goes to urls in usersreg app
    path('user/',include('usersreg.urls'))
]

supporters/urls.py
from django.urls import path
from . import views

app_name = 'supporters'
urlpatterns = [
    path('add_supp/',views.add_supp,name = 'add_supp'),
    path('edit_supp/',views.supp_edited,name = 'supp_edited'),
    path('supp_edited/',views.edit_supp,name = 'edit_supp'),
    path('view_supp/',views.view_supp,name = 'view_supp'),
    path('del_supp/',views.del_supp,name = 'del_supp'),
    path('deleted/',views.delete, name='deleted'),
    path('view_don/',views.view_don,name = 'view_don'),
    path('import/',views.import_supp,name = 'import'),
    path('don_details/',views.view_don,name = 'don_details'),
    path('export/',views.export_supporters,name = 'export_supporters')
    ]

donation/models.py
from django.db import models
# Create your models here.
mode_choces = [
    ('CASH', 'Cash'),
    ('INET', 'Internet Banking'),
    ('UPI', 'UPI'),
    ('IMPS', 'IMPS'),
    ('NEFT', 'NEFT'),
    ('CHEQUE', 'Cheque'),
]
#verified donation model each model is mapped to a unique member
class verified_donation(models.Model):
    rec_no = models.AutoField(primary_key=True)
    # rec_no + prefix = reiciept number
    recipt_num = models.IntegerField(default = 0)
    # member is allowed to be null in case we have an anonymous doner
    member = models.ForeignKey('supporters.supporter', on_delete=models.CASCADE,null=True)
    # optional anon_name of anonymous donor
    anon_name = models.CharField(max_length = 100,null = True,blank =True)
    amount = models.CharField(max_length = 20, blank=False)
    date_donation = models.DateField(blank=True)
    mode_donation = models.CharField(max_length = 100,default = 'CASH',choices = mode_choces)
    date_rec = models.DateField()
    # tells if it was peviously anonymous and now attached to a particular member
    migrated = models.BooleanField(default = False)
    # tells if the model is anonymous
    anon = models.BooleanField(default = False)
    # tells if the mail was successfully sent
    mail_sent = models.BooleanField(default = False)


class misc(models.Model):
    rec_no_prefix = models.IntegerField(default = 0)

donation/forms.py
from django.forms import ModelForm,CharField,DateField,Form,FileField
from .models import verified_donation,misc

# donations which have been verified are cptured using this form directly fetches specified model fields of verified_donation model
class IndonForm(ModelForm):
    class Meta:
        model = verified_donation
        fields = ['amount','mode_donation']

# donations which have are anonymous are cptured using this form directly fetches specified fields of verified_donation model

class AnondonForm(ModelForm):
    amount = CharField(required=True)
    class Meta:
        model = verified_donation
        fields = ['anon_name','amount','mode_donation']

# sets up misc values , this is needed to ensure that the prefix to be added to the reciept number can be changed as needed

class miscForm(ModelForm):
    class Meta:
        model = misc
        fields = ['rec_no_prefix']
    

# form to handle uploaded files

class Uploadfiles(Form):
    file = FileField()

donation/views.py
from django.shortcuts import render,redirect
from supporters.models import supporter
from .forms import IndonForm,AnondonForm
from .models import verified_donation,misc
from django.utils import timezone
from datetime import datetime
from django.views.generic.list import ListView
from django.http import FileResponse,HttpResponseRedirect
from os import remove
import zipfile
from django.urls import reverse
from django.core.mail import EmailMessage
# Create your views here.
from reportlab.pdfgen import canvas
import os
from django.contrib.auth.decorators import login_required
from num2words import num2words
from . import forms
from openpyxl import Workbook
from usersreg.models import member
from django.core.paginator import Paginator

# function to create a pdf file
def hello(f_name,rec_no,name,amount,mode,date,donor_pan,don_address_a,don_address_b,don_address_c):
    print(f_name,rec_no,name,amount,mode,date,donor_pan)
    c = canvas.Canvas(f_name)
    c.drawInlineImage("recFormat.jpg", 40, 20,510,770)
    c.drawString(450,583,str(rec_no))
    c.drawString(210, 552, name)
    #c.drawString(475, 637, str(date_rec))
    c.drawString(150, 525, str(amount)   )
    c.drawString(230, 499, (str(num2words(amount))).capitalize()+"  only")
    if donor_pan:
        c.drawString(260, 453, str(donor_pan))
    if don_address_a:
        c.drawString(220, 426, str(don_address_a))
    if don_address_b:
        c.drawString(220, 416, str(don_address_b))
    if don_address_c:
        c.drawString(220, 406, str(don_address_c))
    c.drawString(270, 355, mode)
    c.drawString(260, 380, str(date))
    c.save()

# view that shows a three options of adding donations when add donation is clicked
# this can be removed by adding a 2nd tier menu to donations
@login_required
def add_don(request):
# this supplies the user with current user and fetched the member for that user
    mem = member.objects.get(user = request.user)
    return render(request,'donation/add_don.html',{"member":mem})

# view for individual donation
@login_required
def don_ind(request):
    mem = member.objects.get(user = request.user)
    if request.method=="GET":
        supp = supporter.objects.all()
        return render(request,'donation/don_ind.html',{"message":"0","supp":supp})
    else:
        obj = request.POST["supp_name"]
        phone = int(obj.split(",")[1])
        obj = supporter.objects.get(phone_no = phone)
        form = IndonForm()
        return render(request,'donation/don_ind.html',{"message":"hello","supporter":obj,'form':form,'member':mem,'mode':'add'})

curr_data = []
#view for bulk donations which just adds elements to the list of supporters
@login_required
def don_bulk(request):
    global curr_data
    mem = member.objects.get(user = request.user)
    supp = supporter.objects.all()
    month = timezone.localdate().month
    year = timezone.localdate().year
    if request.method == "GET":
#        try:
#            type = request.GET["typea"]
#            try:
#                if type == "si":
#                    supp= supporter.objects.filter(is_si = True)
#                elif type == "cons":
#                    supp = supporter.objects.filter(is_constant = True)
#                elif type == "res":
#                    supp = supporter.objects.filter(resources = True)
#                elif type == "spon":
#                    supp = supporter.objects.filter(is_sponsor = True)
#                elif type == "onetime":
#                    supp = supporter.objects.filter(is_one_time=True)
#                else:
#                    supp = supporter.objects.all()
#            except:
#                print("error inie")
#        except:

        request.session["notes"] = []
#        type='all'
#        paginator  = Paginator(supp,20)
#        page = request.GET.get("page")
#        supporters = paginator.get_page(page)
#    return render(request,'donation/don_bulk.html',{"supp":supporters,"month":month,"year":year,'member':mem,'type':type})
        return render(request,'donation/don_bulk.html',{'member':mem,'supp':supp,"month":month,"year":year})
    else:

        sup_to_send = []
        try:
            notes = request.session['notes']
            if request.POST["supp_name"] not in notes:
                notes.append(request.POST["supp_name"])
            request.session['notes'] = notes
            print(request.session["notes"])
        except:
            print("session notes are: none")
            request.session["notes"] = []
        print(request.session['notes'])
        for i in request.session['notes']:
            phone = int(i.split(",")[1])
            obj = supporter.objects.get(phone_no = phone)
            sup_to_send.append(obj)

        print("sup_to_Send")
        return render(request,'donation/don_bulk.html',{'member':mem,'supp':supp,'sup_to_send':sup_to_send,"month":month,"year":year})
# method for anonymous donation addition
@login_required
def don_anon(request):
    mem = member.objects.get(user = request.user)
    if request.method=="GET":
        form = AnondonForm()
        return render(request,'donation/don_anon.html',{"form":form,'member':mem})
    if request.method == "POST":
        form = AnondonForm(request.POST)
        amount = request.POST['amount']
        date = request.POST['date_donation']
        mode = request.POST['mode_donation']
        date_rec = timezone.now()
        anon_don = verified_donation(amount =  amount , date_donation = date , mode_donation = mode , anon = True,date_rec = date_rec)
        anon_name_set=False
        if 'anon_name' in form.changed_data:
            anon_name_set = True
            anon_don.anon_name = request.POST['anon_name']
        anon_don.save()
        anon_don.recipt_num = index_rec_no(anon_don.rec_no)
        anon_don.save()
        if anon_name_set:
            f_name = [str(anon_don.anon_name)+str(anon_don.recipt_num)+'.pdf']
        else:
            f_name = ['No Name -'+str(anon_don.recipt_num)+'.pdf']

        hello(f_name[0],anon_don.recipt_num,str(anon_don.anon_name),anon_don.amount,anon_don.mode_donation,anon_don.date_donation,"","","","")
        try:            #check if save is checked by user
            if request.POST['mail']:
                if len(request.POST['email_id'])>0:
                    send_mail_A([str(request.POST["email_id"])],f_name[0],str(anon_don.anon_name))
                else:
                    send_mail_A(['Kalamenrichinglives@gmail.com'],f_name[0],str(anon_don.anon_name))
        except:
            pass
        try:
            if request.POST["save"]=="True":
                view_val = 'added'
        except:
            os.remove(f_name[0])
            view_val = 'added_none'
            f_name = 'NONE'

        values = [[anon_don.recipt_num,anon_don.anon_name, anon_don.amount, anon_don.date_donation, anon_don.mode_donation,anon_don.date_rec,anon_don.migrated]]
        return render(request,'donation/don_added.html',{"values":values,"f_name":f_name,"view":view_val,'member':mem})

# method that actually adds donations to the database
@login_required
def don_added(request):
    print("inside don added")
    mem = member.objects.get(user = request.user)
    # if type is 0 then individual donation is to be added
    if request.POST["type"]=="0":
        supp = supporter.objects.get(pk = int(request.POST["pk"]))
        rec = verified_donation(member = supp ,
                                amount = request.POST["amount"],
                                date_donation = request.POST["date_donation"],
                                mode_donation = request.POST["mode_donation"],
                                date_rec = timezone.now())
        rec.save()
        rec.recipt_num  = index_rec_no(rec.rec_no)
        rec.save()
        f_name = [str(rec.member.name)+str(rec.recipt_num)+'.pdf']
        hello(f_name[0],rec.recipt_num,rec.member.name,rec.amount,rec.mode_donation,rec.date_donation,rec.member.pan_card,rec.member.address_a,rec.member.address_b, rec.member.address_c)
        try:
            if request.POST['mail']:
                if supp.email_id == None:
                    email = request.POST["email_id"]
                    if len(email)>0:
                        send_mail_A([email],f_name[0],rec.member.name)
                    else:
                        print('mail id not valid')
                else:
                    send_mail_A([supp.email_id],f_name[0],rec.member.name)
        except:
            pass

        try:            #check if save is checked by user
            if request.POST['save']:
                view_val = 'added'
                pass
        except:
            os.remove(f_name[0])
            view_val = 'added_none'
            f_name = 'NONE'
        values = [[rec.recipt_num,rec.member.name, rec.amount, rec.date_donation, rec.mode_donation,rec.date_rec,rec.migrated]]

    # if type is 1 then bulk donation is to be added
    if request.POST["type"]=="1":
        print("type one selected")
        abc = list(request.POST.keys())
        choices = []
        dates = []
        values = []
        f_name=[]
        saves = []
        mails = []
        for choice in abc:
            if 'choice' in choice:
                choices.append(choice.strip('choice'))
            if 'recipt' in choice:
                saves.append(choice.strip('recipt'))
            if 'mail' in choice:
                mails.append(choice.strip('mail'))
        for j in choices:
            dates.append(request.POST['date' + j])
        dates.sort(key=lambda date: datetime.strptime(date, '%Y-%m-%d'))
        sorted_choices = []
        for i in choices:
            date = dates.pop(0)
            for j in choices:
                if j not in sorted_choices:
                    if date == request.POST['date' + j]:
                        sorted_choices.append(j)
        for i in sorted_choices:
            member_id = (request.POST['choice'+i])
            mem_in = supporter.objects.get(pk=member_id)

templates/donation/add_don.html
{% extends 'users/index.html' %}
{% block content %}
<style>
      .options a{
      display:block;
      background-color: white;
      padding:5px;
      text-align:center;
      border:2px solid #2460A7FF;
      width:30%;
      height:5%;
      margin-left:20%;
      margin-top:5%;
      }
</style>
<div class="options">
      <a href="{% url 'donation:don_ind' %}">Individual</a>
      <a href="{% url 'donation:don_anon' %}">Anonymous</a>
      <a href="{% url 'donation:don_bulk' %}">Bulk</a>
</div>
{% endblock %}

templates/donation/don_added.html
{% extends 'users/index.html' %}
{% block content %}
<style>
table, th, td{
    border:1px solid black;
    }
    td,th {
    padding:10px;
    }
</style>

<table >
    <tr>
        <th>Recipt No.</th>
        <th>Name</th>
        <th>Amount</th>
        <th>Donation Date</th>
        <th>Mode</th>
        <th>Recipt Date</th>
        <th>Migrated</th>
    </tr>
    {% for value in values %}
        <tr>
            {% for part in value %}
                <td>{{part}}</td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>
{% if view == 'details' %}
<h1 style="text-align:center;">Total Donation Amount = {{total}}</h1>
{% endif %}
{% if view == 'added'%}
<form method = "POST" action="{% url 'donation:download_rec' %}" target="_blank">
{% csrf_token %}
{% for file_name in f_name %}
<input type="text" hidden value="{{file_name}}" name="file{{forloop.counter}}">
{% endfor %}
{%if view != 'added_none' %}
<input type="submit" value="Download Recipt">
{% endif %}
</form>
{% endif %}
{% endblock %}

templates/donation/don_anon.html
{% extends 'users/index.html' %}
{% block content %}
<form action="{%url 'donation:don_anon' %}" method="POST">
    {% csrf_token %}
    <table>
        <input type="hidden" name = "type" id="type" value="2">
        {{form.as_table}}
    <tr>
        <th><label for = "date_donation" >Date Of Donation</label></th>
        <td><input type = "date" name = "date_donation" id = "date_donation" required></td>
    </tr>
    <tr>
        <th><label for="mail"> Send Mail</label></th>
        <td><input type="checkbox" name="mail" id = "mail" value="True"></td>
    </tr>
    <tr>
        <th><label for="email_id">Email(optional)</label></th>
        <td><input type="email" name="email_id" id = "email_id"></td>
    </tr>
    <tr>
        <th><label for="save">Save Recipt</label></th>
        <td><input type="checkbox" name="save" id = "save" value="True"></td>
    </tr>
    <tr>
        <td>
            <input style = "width:100%;" type="submit" value="Submit">
        </td>
    </tr>
    </table>
</form>
{% endblock %}

templates/donation/don_bulk.html
{% extends 'users/index.html' %}
{% block content %}
<style>
    .inner td{ border: 1px solid;}
</style>
<form  method="POST">
{% csrf_token %}
<label for="name">Name</label>
<input type="text" id="name" list="names_all" name="supp_name" placeholder="Member Name.." >
<datalist id="names_all">
    {% for choice in supp%}
  <option  value="{{choice.name}},{{choice.phone_no}}" ></option>
{%endfor%}
</datalist>
<input type="submit" value="Get">
<!-- 
</form> >
<form action = "{% url 'donation:don_bulk' %}" method="GET">
    <table>
        <tr>
            <td>
                <label for="typea">Select the type to fetch</label>
            </td>
            <td>
                <select id="typea" name="typea">
                    <option value="none">None</option>
                    <option value="all">ALL</option>
                    <option value="si">Standard Instruction</option>
                    <option value="cons">Constant</option>
                    <option value="res">Resources</option>
                    <option value="spon">Sponsor</option>
                    <option value="onetime">One-Time</option>
                </select>
            </td>
            <td>
                <label for="all">All</label>
                <input type="checkbox" name="all" id="all" value="true">
            </td>
            <td>
                <input type = "submit" value = "Get" style="width:100%;border-radius:0px;">
            </td>

        </tr>
    </table>
-->
</form>

<form action = "{% url 'donation:don_added' %}" method="POST">
{% csrf_token %}
    <input type="hidden" name = "type" id="type" value="1">
<table class="inner" style = "width:10%;">
    <tr>
    <th>Please Select</th>
    <th>Name</th>
    <th>Phone Number</th>
    <th>City</th>
    <th>Amount</th>
    <th>Mode</th>
    <th>Donation Date</th>
    <th>Generate Recipt</th>
    <th>Send Mail</th>
</tr>
{% for choice in sup_to_send %}
<tr>
    <td><input type = "checkbox" name="choice{{choice.id}}" id = "choice{{choice.id}}" value = "{{choice.id}}"></td>
    <td><label for = "choice{{choice.id}}" >{{choice.name}}</label></td>
    <td><label for = "choice{{choice.id}}" >{{choice.phone_no}}</label></td>
    <td><label for = "choice{{choice.id}}" >{{choice.city}}</label></td>
    {% if choice.is_constant == True %}
        <td><input style="width:50px;" type="number" id="amount{{choice.id}}" name="amount{{choice.id}}" value = "{{choice.amount}}"></td>
    {% else %}
        <td><input style="width:50px;" type="number" id="amount{{choice.id}}" name="amount{{choice.id}}" placeholder="amount"></td>
    {% endif %}
    <td><select  style="width:80px;" id="mode{{choice.id}}" name="mode{{choice.id}}">
    {% if choice.is_si == True %}
        <option value="inb">Internet Banking</option>
        <option value="ca">Cash</option>
    {% else %}
        <option value="ca">Cash</option>
        <option value="inb">Internet Banking</option>
    {% endif %}
      <option value="chq">Cheque</option>
      <option value="upi">UPI</option>
      <option value="neft">NEFT</option>
      <option value="imps">IMPS</option>

    </select></td>
    {% if choice.is_si == True %}

        {% if choice.si_date < 10 %}
            {% if month < 10 %}
                <td><input type="date" id="date{{choice.id}}" name="date{{choice.id}}" value="{{year}}-0{{month}}-0{{choice.si_date}}" ></td>
            {% else %}
                <td><input type="date" id="date{{choice.id}}" name="date{{choice.id}}" value="{{year}}-{{month}}-0{{choice.si_date}}" ></td>
            {% endif %}
        {% endif %}
        {% if choice.si_date > 9 %}
            {% if month < 10  %}
                <td><input type="date" id="date{{choice.id}}" name="date{{choice.id}}" value="{{year}}-0{{month}}-{{choice.si_date}}" ></td>
            {% else %}
                <td><input type="date" id="date{{choice.id}}" name="date{{choice.id}}" value="{{year}}-{{month}}-{{choice.si_date}}" ></td>
            {% endif %}
        {% endif %}
    {% endif %}

    {% if choice.is_si != True %}
        <td><input type="date" id="date{{choice.id}}" name="date{{choice.id}}" ></td>
    {% endif %}
    <td><input type = "checkbox" name="recipt{{choice.id}}" id = "recipt{{choice.id}}" value = "{{choice.id}}"></td>
    <td><input type = "checkbox" name="mail{{choice.id}}" id = "mail{{choice.id}}" value = "{{choice.id}}"></td>
</tr>
{% endfor %}
</table>
<input type = "submit" value = "Add Donation">
</form>
{% endblock %}

templates/donation/don_bulk_two.html
{% extends 'users/index.html' %}
{% block content %}
<form  method="POST">
{% csrf_token %}
<label for="name">Name</label>
<input type="text" id="name" list="names_all" name="supp_name" placeholder="Member Name.." >
<datalist id="names_all">
	{% for choice in supp%}
  <option  value="{{choice.name}},{{choice.phone_no}}" ></option>
{%endfor%}
</datalist>
<input type="submit" value="Submit">
</form>

{% endblock %}

templates/donation/don_ind.html
{% extends 'users/index.html' %}
{% block content %}
{% if message == '0' %}
<form  method="POST">
{% csrf_token %}
<label for="name">Name</label>
<input type="text" id="name" list="names_all" name="supp_name" placeholder="Member Name.." >
<datalist id="names_all">
{% for choice in supp%}
  <option  value="{{choice.name}},{{choice.phone_no}}" ></option>
{%endfor%}
</datalist>
<input type="submit" value="Submit">
</form>
{% else %}
{% if mode == 'edit' %}
<form action="{% url 'donation:don_edited' %}" method="post">
  <input type = "hidden" name="rec_no" value={{rec.rec_no}}>
{% else %}
<form action="{% url 'donation:don_added' %}" method="post">
<input type="hidden" name = "type" id="type" value="0">
<input type="hidden" name="pk" id="pk" value="{{supporter.pk}}">
{% endif %}
   {% csrf_token %}
  <table style="text-align:right;">
    <tr>
      <th>Name:</th><td>{{supporter.name}}</td>
    </tr>
    <tr>
      <th>Phone:</th><td>{{supporter.phone_no}}</td>
    </tr>
    <tr>
      <th>City:</th><td>{{supporter.city}}</td>
    </tr>
    <tr>
      <th>email:</th><td>{{supporter.email_id}}</td>
    </tr>
  {{form.as_table}}
  {% if mode == 'edit' %}
  <tr>
    <th>
<label for="name">Name</label>
</th>
<td>
<input type="text" id="name" list="names_all" name="supp_name" placeholder="Member Name.." >
<datalist id="names_all">
{% for choice in new_sup%}
  <option  value="{{choice.name}},{{choice.phone_no}}" ></option>
{%endfor%}
</datalist>
</td>
</tr>
    <th>Reciept Date</th><td>{{rec.date_rec}}</td>
    </tr>
    <tr>
    <th>Mail Sent</th><td>{{rec.mail_sent}}</td>
    </tr>
      <tr>
    <th>Migrated</th><td>{{rec.migrated}}</td>
    </tr>
  <tr>
  <th><label for = "old_date_donation">Date Of Donation(Old)</label></th>
  <td>
  <input type = "text" name = "old_date_donation" id = "old_date_donation" 
  value = "{{rec.date_donation.year}}-{{rec.date_donation.month}}-{{rec.date_donation.day}}" disabled="True">
  </td>
  </tr>
  {% endif %}
  <tr>
  <th><label for = "date_donation">Date Of Donation</label></th>
  <td>
  <input type = "date" name = "date_donation" id = "date_donation">
  </td>
  </tr>
    <tr>
        <th><label for="mail"> Send Mail</label></th>
        <td><input type="checkbox" name="mail" id = "mail" value="True"></td>
    </tr>
    <tr>
        <th><label for="email_id">Email(if not present)</label></th>
        <td><input type="email" name="email_id" id = "email_id"></td>
    </tr>
    <tr>
        <th><label for="save">Save Recipt</label></th>
        <td><input type="checkbox" name="save" id = "save" value="True"></td>
    </tr>
  <tr>
    <td>
  <input style = "width:100%;" type="submit" value="Submit">
    </td>
  </tr>
  </table>
</form>
{% endif %}
{% endblock %}

templates/donation/edit_don.html
{% extends 'users/index.html' %}
{% block content %}
<style>
table,th,td {
border:2px solid lightgreen;
border-collapse: collapse;
}
</style>
<form method="POST">
{%csrf_token%}
<table >
	<tr>
	<th>Reciept No</th>
	<th>Member Name</th>
	<th>Amount</th>
	<th>Date of Donation</th>
	<th>Date of Reciept</th>
	<th>Mode of Donation</th>
	<th>Mail Sent</th>
	<th>Select</th>
	</tr>
	{% for dons in don %}
	<tr>
	<td>{{dons.recipt_num}}</td>
	<td>{{dons.member.name}}</td>
	<td>{{dons.amount}}</td>
	<td>{{dons.date_donation}}</td>
	<td>{{dons.date_rec}}</td>
	<td>{{dons.mode_donation}}</td>
	<td>{{dons.mail_sent}}</td>
	<td><button type="submit" name="value" value ={{dons.rec_no}}>Edit</a></td>
	</tr>
	{% endfor %}
</table>
</form>
<div class = "pagination">
    <span class="step_links">
        {% if supp.has_previous %}
            <a href="?page=1&typea={{type}}">&laquo; First</a>
            <a href="?page={{ supp.previous_page_number}}&typea={{type}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{supp.number}} of {{supp.paginator.num_pages}}
        </span>
        {% if supp.has_next %}
            <a href="?page={{supp.paginator.num_pages}}&typea={{type}}">Last &raquo;</a>
            <a href="?page={{supp.next_page_number}}&typea={{type}}">Next</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/donation/edit_misc.html
{% extends 'users/index.html' %}
{% block content %}
<form method = "POST" action="{% url 'donation:edit_misc' %}">
{% csrf_token %}
Current Value : {{value}} <br>
{{form}}
<input type = Submit value = "Submit">
</form>
{% endblock %}

templates/donation/import.html
{% extends 'users/index.html' %}
{% block content %}
<form action="{% url 'supporters:import' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">

</form>
{% endblock %}