donation/urls.py
from django.urls import path,include
from . import views

app_name = 'donation'

urlpatterns = [
# opens three options of adding donations ind bulk or anon
    path('add_don/',views.add_don,name='add_don'),
    path('don_ind/',views.don_ind,name='don_ind'),
    path('don_bulk/',views.don_bulk,name='don_bulk'),
    path('don_anon/',views.don_anon,name='don_anon'),
    path('don_added/',views.don_added,name='don_added'),
    path('view_don/',views.DonationListView.as_view(),name = 'view_don'),
    path('download/',views.download_rec,name = 'download_rec'),
    path('edit_misc/',views.set_prefix,name = 'edit_misc'),
    path('export_donation/',views.export_donation,name = 'export_donations'),
    path('resend_mails/',views.resend_mails,name = 'resend_mail'),
    path('edit_don/',views.edit_don,name = 'edit_don'),
    path('don_edited',views.don_edited,name = 'don_edited')
]

expenditure/urls.py
from django.urls import path
from . import views

app_name = 'expenditure'
urlpatterns=[
    path('addexp/',views.add_exp_view,name = 'add_exp'),
    path('addadv/',views.add_adv,name = 'add_adv'),
    path('expgen/',views.generate_exp,name = 'gen_exp'),
    path('clearexp/',views.clear_exp,name = 'clearexp'),
    path('approvexp/',views.approve_exp,name = 'approvexp'),
    path('myexp/',views.my_exp,name = 'myexp'),
    path('viewexp/',views.view_exp,name = 'viewexp')
]

exptemp/urls.py
from django.urls import path
from . import views

app_name = 'exptemp'
urlpatterns=[
    path('addexp/',views.add_exp_view,name = 'add_exp'),
    path('genexp/',views.success,name = 'generate_exp'),
    path('storeexp/',views.generate_exp,name = 'store_exp'),
    path('appr_success/',views.appr_success,name = 'appr_success'),
 	path('viewexp/',views.view_old,name = 'viewoldexp'),
    path('settleexp/',views.settle_exp,name = 'settleexp'),  
    path('detailexp/<int:key_id>/', views.detail_exp, name='detailexp'),
    path('settleexpform/',views.settle_exp_form,name = 'settleexpform'),
	path('settled/',views.settled_view,name = 'settled'),
]

root_web/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='root'
urlpatterns = [
    #urls of admin site
    path('admin/', admin.site.urls),
    # root url points to the view that opens when there is nothing open
    path('',views.index,name='index'),
    # include the urls of supporters , when 'supp/' us encountered in url django goes to urls in supporter app
    path('supp/',include('supporters.urls')),
      # include the urls of donations , when 'don/' us encountered in url django goes to urls in donations app
    path('don/',include('donation.urls')),
      # include the urls of expenditure , when 'exp/' us encountered in url django goes to urls in expenditure app
    path('exp/',include('exptemp.urls')),
      # include the urls of usersreg , when 'user/' us encountered in url django goes to urls in usersreg app
    path('user/',include('usersreg.urls'))
]

supporters/urls.py
from django.urls import path
from . import views

app_name = 'supporters'
urlpatterns = [
    path('add_supp/',views.add_supp,name = 'add_supp'),
    path('edit_supp/',views.supp_edited,name = 'supp_edited'),
    path('supp_edited/',views.edit_supp,name = 'edit_supp'),
    path('view_supp/',views.view_supp,name = 'view_supp'),
    path('del_supp/',views.del_supp,name = 'del_supp'),
    path('deleted/',views.delete, name='deleted'),
    path('view_don/',views.view_don,name = 'view_don'),
    path('import/',views.import_supp,name = 'import'),
    path('don_details/',views.view_don,name = 'don_details'),
    path('export/',views.export_supporters,name = 'export_supporters')
    ]

usersreg/urls.py
from django.urls import path
from . import views

app_name = 'usersreg'

urlpatterns = [
    path('login/',views.loginu,name='login'),
    path('logout/',views.logoutu,name='logout'),
    path('index/',views.index, name = 'index'),
    path('addmem/',views.add_mem,name='add_mem')
]

templates/index1.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}
.navbar {
  overflow: hidden;
  background-color: #b3c7d6ff;
}
.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}
.subnav {
  float: left;
  overflow: hidden;
}
.subnav .subnavbtn {
  font-size: 16px;
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}
.userinfo {
  font-size: 20px;
  border: 1px blue;
  color: green;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
  float:right;
}
.navbar a:hover, .subnav:hover .subnavbtn {
  background-color: #85b3d1ff;
}
.subnav-content {
  display: none;
  position: absolute;
  left: 0;
  background-color: #2460A7FF;
  width: 100%;
  z-index: 1;
}
.subnav-content a {
  float: left;
  color: white;
  text-decoration: none;
}
.subnav-content a:hover {
  background-color: #eee;
  color: black;
}
.subnav:hover .subnav-content {
  display: block;
}
.main-content{
display:block;
float:top;
width:50%;
margin-left:25%;
margin-right:25%;
margin-top:3%;
padding-left:10%;
background-color:#85b3d1ff;
}
.main-content input[type=submit],#onebut{
width:30%;
height:30px;
margin-left:35%;
margin-top:10px;
border-radius:30px;
background-color:#b3c7d6ff;
}

textarea {width:180px;
height:80px;
}

</style>
</head>
<body>

<div class="navbar">
<div class="userinfo"> Hello,{{request.user}}</div>  
  {% if member.type == "finmem" or member.type == "fihead" or member.type == "dir" %}
  <div class="subnav">
    <button class="subnavbtn">Supporters <i class="fa fa-caret-down"></i></button>
    <div class="subnav-content">
      <a href="{%url  'supporters:add_supp'%}">Add</a>
      <a href="{%url  'supporters:edit_supp'%}">Edit</a>
      <a href="{%url  'supporters:view_supp'%}">View</a>
      <a href="{%url  'supporters:export_supporters'%}">Export</a>
      <a href="{%url  'supporters:import'%}">Import</a>
      {% if member.type == "finhead" or member.type == "dir" %}
      <a href="{%url  'supporters:del_supp'%}">Delete</a>
      <a href=#>Verify</a>
      {% endif %}
    </div>
  </div>
  {% endif %}
   {% if member.type == "finmem" or member.type == "fihead" or member.type == "dir" %}
  <div class="subnav">
    <button class="subnavbtn">Donations <i class="fa fa-caret-down"></i></button>
    <div class="subnav-content">
      <a href="{%url 'donation:add_don' %}">Add</a>
      <a href="{%url 'donation:view_don' %}">View</a>
      <a href="{%url 'donation:view_don' %}">View Unverified</a>
      <a href="{%url 'donation:edit_don' %}">Edit</a>
      <a href="{%url 'donation:resend_mail'%}">Resend Mail</a>
      <a href="{%url  'donation:export_donations'%}">Export</a>
      {% if member.type == "finhead" or member.type == "dir" %}
      <a href=#>Verify</a>
      <a href="{%url 'donation:edit_misc' %}">Edit Misc</a>
      {% endif %}
    </div>
  </div>
  {% endif %}
  <div class="subnav">
    <button class="subnavbtn">Expenditure <i class="fa fa-caret-down"></i></button>
    <div class="subnav-content">
 {% comment %}      <a href="{%url 'expenditure:add_exp' %}">Add Expense</a>
      <a href="{%url 'expenditure:add_adv' %}">Advance</a>
      <a href="{%url 'expenditure:myexp' %}">My Expenses</a>
      {% endcomment %} 
    {% if member.type == "finhead" or member.type == "dir" %}
      <a href="{%url 'exptemp:settleexp' %}">Approve</a>
      {% comment %}
      <!--<a href="{%url 'expenditure:clearexp' %}">Clear</a>-->
      {% endcomment %} 
      <a href="{%url 'exptemp:viewoldexp' %}">View</a>
    {% endif %}
    </div>
  </div>
  {% if member.type == "finhead" or member.type == "dir" %}
    <div class="subnav">
    <button class="subnavbtn">Members <i class="fa fa-caret-down"></i></button>
    <div class="subnav-content">
      <a href="{%url 'usersreg:add_mem'%}">Add</a>
      <a href="#link2">Edit</a>
      <a href="#link3">View</a>
      <a href="#link4">Delete</a>
    </div>
  </div>
  {% endif %}
    <div class="subnav">
    <button class="subnavbtn">Library <i class="fa fa-caret-down"></i></button>
    <div class="subnav-content">
      <a href="#link1">Add</a>
      <a href="#link2">Edit</a>
      <a href="#link3">View</a>
      <a href="#link4">Approve</a>
    </div>
  </div>
  <div class="subnav">
    <button class="subnavbtn">My Profile <i class="fa fa-caret-down"></i></button>
    <div class="subnav-content">
      <a href="#link1">Add</a>
      <a href="#link2">Edit</a>
      <a href="#link3">View</a>
      <a href="{%url 'usersreg:logout'%}">Logout</a>
    </div>
  </div>
</div>

<div class="main-content">
{%block content%}
{%endblock%}
</div>

</body>
</html>